### ISSUE TITLE
ahap data does not include categories

### ISSUE THREAD

**Issue by connorhsm** [connorhsm/ahap.info#1]
Likely something temporary until they're needed, but ideally we should gracefully handle this failure.

```
node process download
--- Processing static-edge ---
Downloading data...
Importing objects...
Object Count: 97
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/home/connorhsm/github/connorhsm/onetech/process/OneLifeData7/categories'
    at Object.readdirSync (node:fs:1452:3)
    at GameData.eachFileInDir (/home/connorhsm/github/connorhsm/onetech/process/src/GameData.js:229:29)
    at GameData.eachFileContent (/home/connorhsm/github/connorhsm/onetech/process/src/GameData.js:237:10)
    at GameData.importCategories (/home/connorhsm/github/connorhsm/onetech/process/src/GameData.js:63:10)
    at MainProcessor.process (/home/connorhsm/github/connorhsm/onetech/process/src/MainProcessor.js:44:14)
    at Object.<anonymous> (/home/connorhsm/github/connorhsm/onetech/process/process.js:14:38)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/connorhsm/github/connorhsm/onetech/process/OneLifeData7/categories'
}

Node.js v18.15.0
```

**Comment by connorhsm** [comment]
Temp fix:
https://github.com/connorhsm/onetech/blob/8ad4fda341e12cf38f6f9e8cb149724882ddf8a2/process/src/MainProcessor.js#L44

**Comment by connorhsm** [comment]
Looks like they got categories, going to close this out as not required.
