### ISSUE TITLE
Static directory not correctly setup before processing takes place

### ISSUE THREAD

**Issue by connorhsm** [connorhsm/ahap.info#2]
I've had plenty of trouble with this for twotech also. Unsure if already fixed.

The traceback is a red herring, its simply that `public/sprite/` is not created before processing.

```
node process download
--- Processing static-edge ---
Downloading data...
Importing objects...
Object Count: 97
Transition Count: 15
Biome Count: 7
Populating versions...
Calculating object depth...
85 objects are uncraftable
Converting sprite images...
Processing sprites...
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/connorhsm/github/connorhsm/onetech/process/../public/static/sprites/sprite_1.png'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at SpriteProcessor.drawSpriteImage (/home/connorhsm/github/connorhsm/onetech/process/src/SpriteProcessor.js:129:18)
    at SpriteProcessor.drawSpriteDirectly (/home/connorhsm/github/connorhsm/onetech/process/src/SpriteProcessor.js:120:10)
    at SpriteProcessor.drawSprite (/home/connorhsm/github/connorhsm/onetech/process/src/SpriteProcessor.js:107:12)
    at SpriteProcessor.renderSprites (/home/connorhsm/github/connorhsm/onetech/process/src/SpriteProcessor.js:70:12)
    at SpriteProcessor.processObject (/home/connorhsm/github/connorhsm/onetech/process/src/SpriteProcessor.js:21:10)
    at SpriteProcessor.process (/home/connorhsm/github/connorhsm/onetech/process/src/SpriteProcessor.js:16:12)
    at GameData.processSprites (/home/connorhsm/github/connorhsm/onetech/process/src/GameData.js:224:15)
    at MainProcessor.process (/home/connorhsm/github/connorhsm/onetech/process/src/MainProcessor.js:60:16) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/connorhsm/github/connorhsm/onetech/process/../public/static/sprites/sprite_1.png'
}

Node.js v18.15.0
```

**Comment by connorhsm** [comment]
Temp fix: Manually create `public/static/sprites/`

**Comment by connorhsm** [comment]
Happens for static-edge also, of course.
